name: VIPKeys
author: Hearlov
main: hearlov\vipkeys\VIPKeys
version: 1.2.7
api: 5.0.0
description: Provides VIP purchase with codes
depend:
 - PurePerms
softdepend:
 - EconomyAPI
 - BedrockEconomy
permissions:
  vipkeys.admin.menu:
    default: op
  vipkeys.admin.menu.newkey:
    default: op
  vipkeys.admin.menu.remkey:
    default: op
  vipkeys.admin.menu.settings:
    default: op
  vipkeys.menu:
    default: true
