---
#lang.yml file in array
language: eng

code-length: 12

#@vips
vips:
 - vip
 - vipplus
 
#economy EconomyAPI
economy: false
#EconomyAPI and BedrockEconomy
economy-plugin: "BedrockEconomy"
givemoney:
 vip: 100
 vipplus: 200

...
